---
title: "requirement summary"
author: "Yufei Zhao"
date: "6/7/2020"
output: html_document
---

## Description of the data (30 points)

* Describe core features of the data
* any additional data you joined in and why
* basic descriptives

* all the variables that were included in your modeling
* how the final analytic dataset was constructed

* Provide a summary of the variables (e.g., how many categorical/continuous variables were included, what were the range of values, etc.), 
* any feature engineering applied to the data


* If missing data are present, discuss how these values were handled, variable transformations, etc. 
* Use this section to explain your data splitting process for model evaluation.

(here from line 25 - 38, we include them in each model post)
## Description of the models fit 

* Describe each model fit
    * answer
* Why the given model was selected
    * answer
* Hyperparameters to be optimized
    * answer
* Assumptions of the model
    * answer
* A high-level (think broad audience) description of what the model is doing and why it is appropriate (even as an initial starting point)
    * answer
* How we evaluate model performance
    * answer

(here from line 43-51, just describe each along the codes)


## Model fits (25 points)

* Describe your model fitting procedure(s) 

(explain the receipe step by step)

* Describe the results of your model evaluation.

(explain the rmse results)


(this part in a separate post)

* Compare and contrast the different fits, including a discussion of model performance
* Share code to communicate your procedures, and *discuss your final model selection* and *the evidence that led you to this selection*.

* You will also need to submit your final model predictions from your final model so that a quantitative indicator of prediction accuracy can be provided.

## Data visualization (10 points)

* Include at least two plots (you may include more) to help communicate your findings. The plots may be of initial data explorations, fits of individual models, and/or plots displaying competing model performance.

