---
title: "Prelim fit 1"
description: |
  A short description of the post.
author:
  - name: Bernice, Peeta, Yufei
    url: https://irisfee.github.io/r4_final_proj/posts/2020-06-06-prelim-fit-1/
date: 06-06-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```
# Read in the data
* Details about the data can be found in another post

```{r}
library(tidyverse)

full_train <- read_csv(here::here("data", "train.csv"),
                       col_types = cols(.default = col_guess(), calc_admn_cd = col_character()))  %>% 
    select(-classification)

str(full_train)

library(rio)
frl <- import("https://nces.ed.gov/ccd/Data/zip/ccd_sch_033_1718_l_1a_083118.zip",
              setclass = "tbl_df")  %>% 
  janitor::clean_names()  %>% 
  filter(st == "OR")  %>%
  select(ncessch, lunch_program, student_count)  %>% 
  mutate(student_count = replace_na(student_count, 0))  %>% 
  pivot_wider(names_from = lunch_program,
              values_from = student_count)  %>% 
  janitor::clean_names()  %>% 
  mutate(ncessch = as.double(ncessch))

stu_counts <- import("https://github.com/datalorax/ach-gap-variability/raw/master/data/achievement-gaps-geocoded.csv",
                     setclass = "tbl_df")  %>% 
  filter(state == "OR" & year == 1718)  %>% 
  count(ncessch, wt = n)  %>% 
  mutate(ncessch = as.double(ncessch))

frl <- left_join(frl, stu_counts)

full_train <- full_train %>% 
    left_join(frl)

sheets <- readxl::excel_sheets("../input/fallmembershipreport/fallmembershipreport_20192020.xlsx")
ode_schools <- readxl::read_xlsx("../input/fallmembershipreport/fallmembershipreport_20192020.xlsx", sheet = sheets[4])

ethnicities <- ode_schools %>%
  select(attnd_schl_inst_id = `Attending School ID`,
         attnd_dist_inst_id = `Attending District Institution ID`,
         sch_name = `School Name`,
         contains("%")) %>%
  janitor::clean_names()

names(ethnicities) <- gsub("x2019_20_percent", "p", names(ethnicities)) 
```


